project:
  type: website
  output-dir: docs

website:
  title: "Brody Regan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - project.qmd
      - hobbies.qmd
      - resume.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    page-layout: full

editor: visual

